pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Check if newest'
                sh 'ls'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
